# Generated by Django 4.1.9 on 2024-06-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailBulletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject',
        ),
    ]
