# Generated by Django 4.1.9 on 2024-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgApiAutopost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TgTokenAutopost', models.CharField(blank=True, max_length=200)),
                ('TgChannelId', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
