# Generated by Django 4.1.9 on 2024-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgApiAutopost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TgTokenAutopost', models.CharField(blank=True, max_length=1000)),
                ('TgChannelId', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VkApiAutopost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VkTokenAutopost', models.CharField(blank=True, max_length=1000)),
                ('VkGroupId', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
