# Generated by Django 4.1.9 on 2024-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_api', '0002_vkapiautopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgapiautopost',
            name='TgTokenAutopost',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vkapiautopost',
            name='VkTokenAutopost',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
