# Generated by Django 4.1.9 on 2023-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPostHidden',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
