# Generated by Django 4.1.9 on 2023-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_show_create_date_post_show_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(blank=True),
        ),
    ]
