# Generated by Django 4.1.9 on 2023-11-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_slug',
            new_name='slug',
        ),
    ]
