# Generated by Django 4.1.9 on 2024-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
