# Generated by Django 4.1.9 on 2024-03-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='page',
            old_name='isPostHidden',
            new_name='is_page_hidden',
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_telegram',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_to_vk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='post_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.posttype'),
        ),
    ]
