# Generated by Django 4.1.9 on 2023-06-30 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Counter',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.TextField(max_length=100, null=True)),
                ('surname', models.TextField(max_length=100, null=True)),
                ('patronymic', models.TextField(max_length=100, null=True)),
                ('vk_id', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('phonenumber', models.CharField(max_length=11, null=True)),
                ('other_contacts', models.TextField(blank=True, max_length=100, null=True)),
                ('have_whatsapp', models.BooleanField(default=False, null=True)),
                ('have_telegram', models.BooleanField(default=False, null=True)),
                ('have_viber', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_employer', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('isArchived', models.BooleanField(blank=True, null=True)),
                ('have_whatsapp', models.BooleanField(default=False)),
                ('have_viber', models.BooleanField(default=False)),
                ('have_telegram', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=11, null=True)),
                ('target', models.TextField()),
                ('stage', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
