# Generated by Django 4.1.9 on 2023-06-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.TextField(max_length=100, null=True)),
                ('surname', models.TextField(max_length=100, null=True)),
                ('patronymic', models.TextField(max_length=100, null=True)),
                ('vk_id', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('phonenumber', models.DecimalField(decimal_places=0, max_digits=11, null=True)),
                ('other_contacts', models.TextField(max_length=100, null=True)),
                ('have_whatsapp', models.BooleanField(default=False, null=True)),
                ('have_telegram', models.BooleanField(default=False, null=True)),
                ('have_viber', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_employer', models.BooleanField(default=False, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.DecimalField(decimal_places=0, max_digits=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('main_description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('main_image', models.ImageField(upload_to='vacancy_images')),
                ('additional_images', models.ManyToManyField(blank=True, to='MyCareer.additionalimage')),
                ('career_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='MyCareer.careercenter')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('career_centers', models.ManyToManyField(related_name='messengers', to='MyCareer.careercenter')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target', models.TextField()),
                ('stage', models.TextField()),
                ('result', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac', to=settings.AUTH_USER_MODEL)),
                ('have_telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_tg', to=settings.AUTH_USER_MODEL)),
                ('have_viber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_vb', to=settings.AUTH_USER_MODEL)),
                ('have_whatsapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_wa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
