# Generated by Django 4.1.9 on 2023-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Counter',
            },
        ),
    ]
