# Generated by Django 4.1.9 on 2023-06-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerCenter',
        ),
    ]
