# Generated by Django 4.1.9 on 2023-06-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0002_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='stage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
