# Generated by Django 4.1.9 on 2023-06-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0002_delete_careercenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='have_telegram',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='have_viber',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='have_whatsapp',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='phonenumber',
        ),
    ]
