# Generated by Django 4.1.9 on 2023-06-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0003_remove_demand_have_telegram_remove_demand_have_viber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='faculty',
        ),
    ]
