# Generated by Django 4.1.9 on 2023-09-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0004_remove_demand_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
