# Generated by Django 4.1.9 on 2023-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0005_userprofile_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recordbook',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
