# Generated by Django 4.1.9 on 2023-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0009_survey_description_after_passing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый вопрос'), ('single_choice', 'Выбор одного варианта'), ('multiple_choice', 'Выбор нескольких вариантов')], default='text', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_ended_study',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_ending',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
