# Generated by Django 4.1.9 on 2023-11-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0010_remove_answer_answer_text_answer_answer_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
