# Generated by Django 4.1.9 on 2023-11-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0011_remove_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_employer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
