# Generated by Django 4.1.9 on 2024-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCareer', '0012_userprofile_company_userprofile_is_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreed_for_email_bulletins',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
